### ISSUE TITLE
Bug Playerlist

### ISSUE THREAD

**Issue by Bratwurscht** [Bratwurscht/tournament-manager#5]
In commit ab358d7 in Datei 
```
tournament-manager/src/main/java/backend/PlayerList.java
```
ab Zeile 35 werden alle Spielernamen zurückgegeben. 

Funktion ist nicht sinnvoll, auch bei weiterer Entwicklung. Frontend bzw. Console muss Namen in Abhängigkeit der der ID ersetzen, da sonst rückwirkend die Zuordnung nicht sichergestellt werden kann. Im Backend sollte ausschließlich mit den IDs gearbeitet werden.

**Comment by Marceko** [comment]
Methoden getPlayerNames(ArrayList<Integer> playerIds) und getAllPlayerNames() entfernt. War zum testen gedacht, da Evaluation von .json Datei sonst schwierig nachvollziehbar.
